#!/bin/bash

# prompt with format: [usr@host pwd]
# PS1="[\[\033[32m\]\u\[\033[1;34m\]@\h \[\033[0;37m\]\w]\$ \[\033[0m\]"

git_branch() {
    git branch 2>/dev/null | grep '^*' | colrm 1 2
}
# prompt with format: [time usr@host pwd on git_branch]
PS1="\n[ \[\033[95m\]\t \[\033[1;32m\]\u\[\033[1;34m\]@\h \[\033[0;37m\]\w \[\033[1;34m\]on \[\033[0;91m\]\$(git_branch)\[\033[0;37m\] ]\n\$ \[\033[0m\]"

# disable ctrl+S and ctrl+Q
stty -ixon

# set enviroment stuff
export NLS_LANG="American_America.UTF8"

# software in url local bin takes priority
export PATH=/usr/local/bin:$PATH

# to work with 256 colors
export TERM="xterm-256color"

# colors for ls
export LS_COLORS="di=94;40:ln=31;40:so=35;40:pi=33;40:ex=92;40:bd=34;46:cd=34;43:su=0;41:sg=0;46:tw=0;42:ow=0;43:"
export EDITOR="vim"
unset SSH_ASKPASS

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# For Mac
#export CLICOLOR=1
#export LSCOLORS=GxFxhxbxcxHbHehghfacxc
#alias ls="ls -G"

# source external scripts
# source ~/.proxyon

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend
# set history length
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

